import { useEffect, useMemo, useState } from "react";
const API="/api";
type Props={token:string};
const steps=['SUBMITTED','AI_ANALYZED','INSTITUTIONS_MATCHED','ADOPTED','SOLUTION_DEVELOPMENT','SOLUTION_PROPOSED','IMPLEMENTATION','RESOLVED'];
const label=(x:string)=>x.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
export default function Government({token}:Props){
 const h={Authorization:`Bearer ${token}`}; const [data,setData]=useState<any>(null); const [tickets,setTickets]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [busy,setBusy]=useState(false); const [tab,setTab]=useState<'queue'|'overview'|'organizations'>('queue');
 async function load(){try{const [a,b,c]=await Promise.all([fetch(`${API}/government/dashboard`,{headers:h}),fetch(`${API}/government/challenges?limit=100`,{headers:h}),fetch(`${API}/government/organizations`,{headers:h})]);const ad=await a.json(),bd=await b.json(),cd=await c.json();if(a.ok&&b.ok&&c.ok){setData({...ad,organizations:cd.organizations||[]});setTickets(bd.challenges||[]);setSelected((old:any)=>old&&bd.challenges?.find((x:any)=>x.id===old.id)||bd.challenges?.[0]||null)}}catch{}}
 useEffect(()=>{load()},[]);
 async function moderate(id:string,status:string){setBusy(true);try{await fetch(`${API}/government/challenges/${id}/moderation`,{method:'PATCH',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify({status,reason:status==='HIDDEN'?'Hidden by government moderation':''})});await load()}finally{setBusy(false)}}
 async function verify(id:string,verified:boolean){setBusy(true);try{await fetch(`${API}/government/organizations/${id}`,{method:'PATCH',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify({verified})});await load()}finally{setBusy(false)}}
 const current=selected?.status||'SUBMITTED'; const stepIndex=Math.max(0,steps.indexOf(current));
 const districts=useMemo(()=>data?.districts||[],[data]);
 if(!data)return <section className="page-panel"><div className="loading-state">Loading command center…</div></section>;
 return <section className="command-center page-panel"><div className="command-head"><div><div className="hero-kicker">ADMINISTRATION</div><h1>Issue command center</h1><p>Review live public issues, follow institutional action and monitor outcomes from one operational workspace.</p></div><div className="command-kpis"><span><b>{data.kpis.total_challenges}</b>Open reports</span><span><b>{data.kpis.urgent_open}</b>Urgent</span><span><b>{data.kpis.resolved_challenges}</b>Resolved</span></div></div>
 <div className="command-tabs"><button className={tab==='queue'?'active':''} onClick={()=>setTab('queue')}>Issue queue</button><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='organizations'?'active':''} onClick={()=>setTab('organizations')}>Partners</button></div>
 {tab==='queue'&&<div className="ticket-layout"><aside className="ticket-list">{tickets.map(t=><button key={t.id} className={selected?.id===t.id?'ticket active':'ticket'} onClick={()=>setSelected(t)}><div><span className={`severity ${t.urgency_hint.toLowerCase()}`}>{t.urgency_hint}</span><small>{t.district||'Jharkhand'} · {t.category||'Uncategorised'}</small></div><strong>{t.title}</strong><span className="ticket-status">{label(t.status)}</span></button>)}{tickets.length===0&&<div className="empty">No tickets in the queue.</div>}</aside><article className="ticket-detail">{selected?<><div className="detail-top"><div><div className="hero-kicker">TICKET</div><h2>{selected.title}</h2><p>{selected.description}</p><div className="detail-meta">{selected.category} · {selected.request_type} · {selected.district||'Location not supplied'}{selected.block?` · ${selected.block}`:''}</div></div><div className="detail-actions"><button className="secondary-btn" disabled={busy} onClick={()=>moderate(selected.id,'HIDDEN')}>Hide</button><button className="secondary-btn" disabled={busy} onClick={()=>moderate(selected.id,'VISIBLE')}>Restore</button></div></div><div className="status-card"><div className="status-card-head"><strong>Progress</strong><span>{label(current)}</span></div><div className="status-track">{steps.map((s,i)=><div key={s} className={i<=stepIndex?'status-step done':'status-step'}><i>{i<stepIndex?'✓':i===stepIndex?'•':''}</i><span>{label(s)}</span></div>)}</div></div><div className="detail-grid"><div><span>Reporter</span><strong>{selected.citizen_name||'Private citizen'}</strong></div><div><span>Urgency</span><strong>{selected.urgency_hint}</strong></div><div><span>Moderation</span><strong>{selected.moderation_status||'VISIBLE'}</strong></div><div><span>Reported</span><strong>{new Date(selected.created_at).toLocaleDateString()}</strong></div></div></>:<div className="empty large-empty">Select a ticket to inspect its progress.</div>}</article></div>}
 {tab==='overview'&&<div className="admin-overview"><div className="admin-card"><h3>District load</h3>{districts.map((d:any)=><div className="admin-bar" key={d.district}><span>{d.district}</span><div><i style={{width:`${Math.max(4,Math.round(d.challenges/Math.max(1,...districts.map((x:any)=>x.challenges))*100))}%`}}/></div><b>{d.challenges}</b></div>)}</div><div className="admin-card"><h3>Impact</h3><div className="big-metrics"><div><b>{data.impact.people_affected}</b><span>People affected</span></div><div><b>{data.impact.villages_affected}</b><span>Villages affected</span></div><div><b>{data.impact.time_saved_hours}</b><span>Hours saved</span></div></div></div></div>}
 {tab==='organizations'&&<div className="partner-grid">{(data.organizations||[]).map((o:any)=><article className="partner-card" key={o.id}><div className="partner-top"><span className={o.verified?'verified':'unverified'}>{o.verified?'VERIFIED':'REVIEW'}</span><small>{label(o.organization_type)}</small></div><h3>{o.name}</h3><p>{o.description||'No description provided.'}</p><div className="partner-stats"><span><b>{o.average_rating||0}</b> rating</span><span><b>{o.rating_count||0}</b> reviews</span><span><b>{o.member_count||0}</b> members</span></div><button className="secondary-btn" disabled={busy} onClick={()=>verify(o.id,!o.verified)}>{o.verified?'Revoke verification':'Verify partner'}</button></article>)}</div>}
 </section>
}
